# Generated by Django 4.2.15 on 2024-08-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='partysize',
            field=models.SmallIntegerField(),
        ),
    ]
